version: '3'
services:
  compile: &defaults
    build: .
    volumes:
      - .:/home/mruby/code:rw
    command: rake compile
  clean:
    <<: *defaults
    command: rake clean
  shell:
    <<: *defaults
    command: bash
