name: docker
on:
  push:
    branches:
      - master
    tags:
      - v*
  pull_request:
    branches:
      - '*'
  schedule:
    - cron: "30 15 * * *" # 7:30 PST (-8), 8:30 PDT (-7)
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Install libraries
        run: sudo apt-get install ruby-bundler bison git libonig-dev
      - uses: actions/checkout@v2
      - run: bundle install -j$(nproc)

      - name: Integration test
        run: bundle exec rake test:integration

  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [linux, darwin, windows]
        arch: [x86_64, i686, i386, armhf, aarch64]
        exclude:
          - os: linux
            arch: i386
          - os: darwin
            arch: i686
          - os: darwin
            arch: armhf
          - os: darwin
            arch: aarch64
          - os: windows
            arch: i386
          - os: windows
            arch: armhf
          - os: windows
            arch: aarch64
      fail-fast: false
    steps:
      - name: Install libraries
        run: sudo apt-get install ruby-bundler bison git libonig-dev
      - uses: actions/checkout@v2
      - run: bundle install -j$(nproc)

      - name: Build ${{ matrix.os }}-${{ matrix.arch }} binary
        run: bundle exec rake release:build:${{ matrix.os }}-${{ matrix.arch }} release:compress

      - name: Upload artifacts
        uses: actions/upload-artifact@v1
        with:
          name: mitamae-${{ matrix.arch }}-${{ matrix.os }}
          path: mitamae-build/

  release:
    runs-on: ubuntu-latest
    needs:
      - test
      - build
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - uses: actions/download-artifact@v1
        with:
          name: mitamae-x86_64-linux
          path: mitamae-build/
      - uses: actions/download-artifact@v1
        with:
          name: mitamae-i686-linux
          path: mitamae-build/
      - uses: actions/download-artifact@v1
        with:
          name: mitamae-armhf-linux
          path: mitamae-build/
      - uses: actions/download-artifact@v1
        with:
          name: mitamae-aarch64-linux
          path: mitamae-build/
      - uses: actions/download-artifact@v1
        with:
          name: mitamae-x86_64-darwin
          path: mitamae-build/
      - uses: actions/download-artifact@v1
        with:
          name: mitamae-i386-darwin
          path: mitamae-build/
      - uses: actions/download-artifact@v1
        with:
          name: mitamae-x86_64-windows
          path: mitamae-build/
      - uses: actions/download-artifact@v1
        with:
          name: mitamae-i686-windows
          path: mitamae-build/

      - name: Release
        run: |
          export VERSION=$(echo "$GITHUB_REF" | sed -e 's!refs/tags/!!')
          curl -L "https://github.com/tcnksm/ghr/releases/download/${GHR_VERSION}/ghr_${GHR_VERSION}_linux_amd64.tar.gz" | tar xvz
          "ghr_${GHR_VERSION}_linux_amd64/ghr" -u itamae-kitchen -r mitamae -replace -n "$VERSION" "$VERSION" mitamae-build/
        env:
          GHR_VERSION: v0.13.0
          GITHUB_TOKEN: ${{ secrets.githubtoken }}
